### ISSUE TITLE
create login page

### ISSUE THREAD

**Issue by ParthasarathiPanda** [ParthasarathiPanda/LMS-12PM-DEVOPS-PROJ1#2]
create login page

add some img
submit and cancel button
forget password link

![login page](https://github.com/ParthasarathiPanda/LMS-12PM-DEVOPS-PROJ1/assets/97597630/1f3b7333-d7fd-4049-bd3c-07a2ae658c30)

**Comment by Partha-2000-Snp** [comment]
working on it
